### PR TITLE
Create project

### PR DESCRIPTION
**Pull request by non-binary**
Getting started steps for Garnet.

### CODE REVIEW

**Comment by non-binary** [comment]
I'm using the https://github.com/zamith/heroku-buildpack-crystal buildpack for Heroku.

**Comment by non-binary** [comment]
Crystal was running `/src/garnet.cr` in the spec step which started a web server. Something we don't want when unit testing as we'll be testing underneath the web server. Commented out the requirement for that file for now in the `spec/spec_helper.cr` file.

This didn't work so I'm trying removing the custom port declaration since I've seen other folks run the tests successfully and they didn't have this in their code.

**Comment by non-binary** [comment]
The build for 63038ac is going to fail but it's because of the fake test. Thanks again @jgaskins!

**Comment by jgaskins** [comment]
Glad I could help!

**Comment by non-binary** [comment]
I'm trying another buildpack since the Heroku build failed due to a Kemal issue I'm not seeing locally. We'll see if this helps and if not we have another debugging adventure on our hands. 🤷‍♀️

**Comment by non-binary** [comment]
This should also fix the head detached warning.

**Comment by non-binary** [comment]
The Travis build is passing but the Heroku deployment is failing. Going to have to investigate this some more. Going to have dinner and I'll check it out when I get back or maybe tomorrow. 🤔

**Comment by non-binary** [comment]
The deploy issues are a separate problem. Going to merge this and continue debugging in another branch.

**Pull request merged**
